name: Build GM-PRO 86 Binaries

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install ESP8266 Platform (SDK 2.0.0)
        run: |
          arduino-cli core update-index
          arduino-cli core install esp8266:esp8266@2.0.0 --additional-urls http://arduino.esp8266.com/stable/package_esp8266com_index.json

      - name: Install Legacy Libraries
        run: |
          # Paksa install versi lama agar tidak bentrok dengan SDK 2.0.0
          arduino-cli lib install "Adafruit GFX Library"@1.10.10
          arduino-cli lib install "Adafruit SSD1306"@2.4.6
          arduino-cli lib install "Adafruit BusIO"@1.7.0

      - name: Compile Sketch
        run: |
          arduino-cli compile --fqbn esp8266:esp8266:generic --output-dir ./build ./GMpro86.ino

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: GMPRO86-BIN-SDK2.0.0
          path: ./build/*.bin
